# Generated by Django 4.1.7 on 2023-05-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_teacheruser_studentuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacheruser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.DeleteModel(
            name='TeacherUser',
        ),
    ]
