# Generated by Django 4.1.7 on 2023-05-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Home', '0005_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
