# Generated by Django 4.2 on 2023-05-18 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0011_alter_staff_user_alter_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="user",
        ),
        migrations.RemoveField(
            model_name="student",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
