# Generated by Django 4.2 on 2023-05-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("Home", "0012_remove_staff_user_remove_student_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="groups",
            field=models.ManyToManyField(related_name="students", to="auth.group"),
        ),
    ]
