# Generated by Django 4.2 on 2023-05-24 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0015_remove_staff_user_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finance",
            name="remaining_fee",
        ),
    ]
