# Generated by Django 4.2 on 2023-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0016_remove_finance_remaining_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="finance",
            name="fee_submitted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
