# Generated by Django 4.2 on 2023-05-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0017_finance_fee_submitted_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finance",
            name="total_fee",
        ),
        migrations.AddField(
            model_name="course",
            name="total_fee",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
