# Generated by Django 4.2 on 2023-05-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0020_alter_enrollment_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="gender",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
