# Generated by Django 4.2 on 2023-06-09 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0022_bookissue_staff"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("enrollment", "date")},
        ),
    ]
